FoodMenuApp/FoodMenuApp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    ## whenever the URL has food/, it tells the router to go look at the router in food folder called food.urls
    path('food/', include('food.urls')),
]

FoodMenuApp/food/urls.py
from django.urls import path
from . import views

app_name= 'food' ##for django to know which app to look out for when a /index or /detail is called as other apps might have the same router name
urlpatterns = [
    ## for /food/
    path("", views.index, name="index"),
    ## for /food/hello/
    path("hello/", views.index,name='index'),
    path("item/", views.item, name='item'),
    ## for /food/1
    path('<int:item_id>/',views.detail,name='detail'), ##path that expects an int that is called item_id that will be passed to the detail controller as input


]

FoodMenuApp/food/models.py
from django.db import models

"""Models are classes  in python. They are just blueprints (schemas) to make database tables.

Eg. To create a model student, simple create a class named Student"""

class Item(models.Model):

    ##format the output when we run Item.object.all()
    def __str__(self):
        return self.item_name

    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://archive.org/download/placeholder-image/placeholder-image.jpg")

FoodMenuApp/food/views.py
from django.shortcuts import render, HttpResponse
from django.http import HttpResponse
from .models import Item
from django.template import loader
# Create your views for food/ here.

##index view 
def index(request):
    item_list= Item.objects.all()
    # template= loader.get_template('food/index.html')
    ##template needs a context from the db
    context={
        'item_list': item_list, ##item_list is passed to the html
    }
    # return HttpResponse('Hello World')
    # return HttpResponse(item_list)
    #return HttpResponse(template.render(context,request))
    ##OR
    return render(request, 'food/index.html', context) ## pass the path to templaye and context to the render

def item(request):
    return HttpResponse("<h1>This is an item view</h1>")


def detail(request,item_id):
    item= Item.objects.get(pk=item_id)
    context= {
        'item':item,
    }
    return render(request,'food/detail.html', context)

FoodMenuApp/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>

        <div class="navbar-nav ms-auto d-flex flex-row">
            <a class="nav-item nav-link text-light mx-2" href="#">Menu</a>
            <a class="nav-item nav-link text-light mx-2" href="#">Login</a>
            <a class="nav-item nav-link text-light mx-2" href="#">Item</a>
        </div>

     </nav>

    {% block body %}

    {% endblock %}
    
</body>
</html>

FoodMenuApp/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="300px" src="{{item.item_image}}" class="card/">
        </div>
        <div class="col-md-6">
            <h1>{{item.item_name}}</h1>
            <h2>{{ item.item_desc }}</h2>
            <h3>price: {{item.item_price }}</h3>
        </div>
    </div>

</div>
<!-- <h1>{{item.item_name}}</h1>
<h2>{{ item.item_desc }}</h2>
<h3>price: {{item.item_price }}</h3> -->
{% endblock %}

FoodMenuApp/food/templates/food/index.html
{% extends 'food/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>


</head>
<body>

    {% block body %}
    {% for item in item_list %}
    <div class="row">
        <!-- Image Section -->
        <div class="col-md-3 offset-md-2" >
            <img class="card img-fluid" height="10px" src="https://media.istockphoto.com/id/1442417585/photo/person-getting-a-piece-of-cheesy-pepperoni-pizza.jpg?s=612x612&w=0&k=20&c=k60TjxKIOIxJpd4F4yLMVjsniB4W1BpEV4Mi_nb4uJU=" alt="Pizza">
        </div>
    
        <!-- Text Section -->
        <div class="col-md-4 offset-md-1">
            <h3>{{ item.item_name }}</h3>
            <h5>{{ item.item_desc }}</h5>
            <h6>${{ item.item_price }}</h6>
        </div>
    
        <!-- Button Section -->
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">View Details</a>
        </div>
    </div>
    
    
    {% endfor %}

    {% endblock %}
</body>
</html>